import { useEffect, useMemo, useState } from "react";
import { createFileRoute, useSearch } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { z } from "zod";
import { toast } from "sonner";
import { Check, CircleAlert, Save, X } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { findSession, getClasses, getSessionEntries, getStudents, saveHomework } from "@/lib/data";
import { HW_STATUSES, STATUS_META, todayISO, type HwStatus } from "@/lib/hw";
import { PageHeader, EmptyState, ErrorBlock, LoadingBlock } from "@/components/common";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/_authenticated/homework")({ validateSearch: z.object({ classId: z.string().optional() }), head: () => ({ meta: [{ title: "Take Homework — School Homework Tracker" }] }), component: HomeworkPage });

function HomeworkPage() {
  const { user } = useAuth(); const search = useSearch({ from: "/_authenticated/homework" }); const qc = useQueryClient();
  const [classId, setClassId] = useState(search.classId ?? ""); const [subjectId, setSubjectId] = useState(""); const [date, setDate] = useState(todayISO()); const [marks, setMarks] = useState<Record<string, { status: HwStatus; remarks: string }>>({}); const [existing, setExisting] = useState<{ id: string } | null>(null);
  const classes = useQuery({ queryKey: ["classes"], queryFn: getClasses }); const selected = classes.data?.find((item) => item.id === classId); const students = useQuery({ queryKey: ["students", classId], queryFn: () => getStudents(classId), enabled: Boolean(classId) });
  const duplicate = useQuery({ queryKey: ["session", classId, subjectId, date], queryFn: () => findSession(classId, subjectId, date), enabled: Boolean(classId && subjectId && date) });
  const existingEntries = useQuery({ queryKey: ["session-entries", duplicate.data?.id], queryFn: () => getSessionEntries(duplicate.data!.id), enabled: Boolean(duplicate.data?.id) });
  useEffect(() => { if (duplicate.data?.id) setExisting(duplicate.data); else setExisting(null); }, [duplicate.data]);
  useEffect(() => { if (students.data) setMarks(Object.fromEntries(students.data.map((student) => [student.id, { status: "not_submitted" as HwStatus, remarks: "" }]))); }, [students.data]);
  useEffect(() => { if (existingEntries.data) setMarks((current) => Object.fromEntries(Object.entries(current).map(([id, value]) => { const found = existingEntries.data.find((entry) => entry.student_id === id); return [id, found ? { status: found.status, remarks: found.remarks ?? "" } : value]; }))); }, [existingEntries.data]);
  const tally = useMemo(() => HW_STATUSES.map((status) => [status, Object.values(marks).filter((mark) => mark.status === status).length] as const), [marks]);
  const save = useMutation({ mutationFn: () => saveHomework({ sessionId: existing?.id, classId, subjectId, teacherId: user!.id, date, marks: Object.entries(marks).map(([student_id, value]) => ({ student_id, ...value })) }), onSuccess: () => { toast.success("Homework saved successfully"); qc.invalidateQueries({ queryKey: ["session", classId, subjectId, date] }); qc.invalidateQueries({ queryKey: ["entries"] }); }, onError: (e: Error) => toast.error(e.message) });
  function markAll(status: HwStatus | null) { setMarks((current) => Object.fromEntries(Object.entries(current).map(([id, value]) => [id, { ...value, status: status ?? "not_submitted" }]))) }
  return <div><PageHeader title="Take Homework" description="Mark every student quickly and save one session per class, subject and date." actions={<Button onClick={() => save.mutate()} disabled={!classId || !subjectId || !students.data?.length || save.isPending}><Save className="size-4" /> {save.isPending ? "Saving…" : existing ? "Update homework" : "Save homework"}</Button>} />
    <div className="grid gap-4 md:grid-cols-3"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={classId} onChange={(e) => { setClassId(e.target.value); setSubjectId(""); }}><option value="">Select class</option>{(classes.data ?? []).map((item) => <option key={item.id} value={item.id}>{item.class_name}</option>)}</select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={subjectId} onChange={(e) => setSubjectId(e.target.value)} disabled={!selected}><option value="">Select subject</option>{(selected?.subjects ?? []).map((subject) => <option key={subject.id} value={subject.id}>{subject.subject_name}</option>)}</select><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></div>
    {existing ? <div className="mt-4 flex items-center gap-2 rounded-lg border border-warning/40 bg-warning/10 p-3 text-sm"><CircleAlert className="size-4" /> Homework already exists for this class, subject and date. Editing the existing session.</div> : null}
    {!classId || !subjectId ? <EmptyState title="Choose a class and subject" description="Students will load automatically after both are selected." /> : students.isLoading ? <LoadingBlock rows={5} /> : students.error ? <ErrorBlock error={students.error as Error} /> : !students.data?.length ? <EmptyState title="No students found in this class." /> : <><div className="my-4 flex flex-wrap gap-2">{HW_STATUSES.map((status) => <Button key={status} type="button" variant="outline" size="sm" onClick={() => markAll(status)}>{STATUS_META[status].short} Mark all {STATUS_META[status].label}</Button>)}<Button type="button" variant="ghost" size="sm" onClick={() => markAll(null)}><X className="size-4" /> Clear all</Button></div><div className="divide-y rounded-xl border">{(students.data ?? []).map((student) => { const mark = marks[student.id] ?? { status: "not_submitted" as HwStatus, remarks: "" }; return <div key={student.id} className="grid gap-3 p-4 md:grid-cols-[70px_1fr_2fr_1fr] md:items-center"><div className="text-sm font-medium">#{student.roll_number}</div><div className="font-medium">{student.student_name}</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{HW_STATUSES.map((status) => <Button key={status} type="button" size="sm" variant={mark.status === status ? "default" : "outline"} className={mark.status === status ? STATUS_META[status].button : ""} onClick={() => setMarks((current) => ({ ...current, [student.id]: { ...mark, status } }))}>{STATUS_META[status].short} <span className="hidden sm:inline">{STATUS_META[status].label}</span></Button>)}</div><Input placeholder="Remarks (optional)" value={mark.remarks} onChange={(e) => setMarks((current) => ({ ...current, [student.id]: { ...mark, remarks: e.target.value } }))} /></div> })}</div><div className="mt-4 flex flex-wrap gap-3 text-sm">{tally.map(([status, count]) => <span key={status} className="rounded-full border px-3 py-1">{STATUS_META[status].short} {STATUS_META[status].label}: {count}</span>)}</div></>}
  </div>;
}