REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.owns_class(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.owns_session(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.owns_student(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.owns_class(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owns_session(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owns_student(uuid) TO authenticated;